sudo: false

language: node_js
node_js: 10

cache: yarn

install:
  - yarn install --frozen-lockfile

script:
  - yarn run format:check
  - yarn run build:prod

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
