sudo: false

language: node_js
node_js: 10

install:
  - npm ci

script:
  - npm run format:check
  - npm run build:prod

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
